Traceback (most recent call last):
  File "/home/fud3/Documents/git/3y3/./dados.py", line 44, in <module>
    relatorio.write_processes(process_list)
  File "/home/fud3/Documents/git/3y3/relatorio.py", line 46, in write_processes
    writer_processes.writerow(proc)
  File "/usr/lib/python3.11/csv.py", line 154, in writerow
    return self.writer.writerow(self._dict_to_list(rowdict))
                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/csv.py", line 149, in _dict_to_list
    raise ValueError("dict contains fields not in fieldnames: "
ValueError: dict contains fields not in fieldnames: 'cpu_percent', 'username', 'memory_percent', 'name', 'pid'
